image: gitpod/workspace-full
tasks:
  - init: docker-compose up -d
ports:
  - port: 3000
    onOpen: open-preview
  - port: 4000
    onOpen: ignore
  - port: 5000
    onOpen: ignore
  - port: 6000
    onOpen: ignore
  - port: 80
    onOpen: ignore
  - port: 443
    onOpen: ignore
